co-bbu/co-bbu-programmers

2단계/의상/jaeheon.js, 2단계/캐시/jaeheon.js
의상: 해시맵 활용, 문제 없음
캐시: LRU 알고리즘 이해, 문제 없음
=> 재헌: 캐시, 의상

2단계/괄호 회전하기/minjeong.js, 2단계/구명보트/minjeong.js
각 문제에 해당하는 폴더에 본인 이름 파일을 생성하여 문제 풀이를 올려 주시면 됩니다.
=> 각 문제 폴더 생성

2단계/주차 요금 계산/jaeheon.js, 2단계/피로도/jaeheon.js
Jaeheon's 커밋 메세지 컨벤션
재헌: [문제 이름][난이도]
난이도
- 별 0개(빈칸): 스스로 해결한 문제
- 별 1개(*): 다른 사람의 글로 된 풀이 참고(코드 참고 X)
- 별 2개(**): 다른 사람의 글로 된 풀이와 코드 참고
- 별 3개(***): 다른 사람의 글로 된 풀이와 코드 참고 + 그래도 이해가 안되거나 오랜 시간이 걸린 문제
주차 요금 계산: 해시맵 활용, 문제 없음
피로도: dfs를 이용한 완전탐색, 다른 사람의 코드 참고
=> 재헌: 주차 요금 계산, 피로도

1단계/K번째 수/jaeheon.js, 1단계/모의고사/jaeheon.js, 1단계/비밀지도/jaeheon.js, 1단계/삼총사/jaeheon.js, 1단계/숫자 짝꿍/jaeheon.js, 1단계/신고 결과 받기/jaeheon.js, 1단계/실패율/jaeheon.js, 1단계/완주하지 못한 선수/jaeheon.js, 1단계/제일 작은 수 제거하기/jaeheon.js, 1단계/체육복/jaeheon.js, 1단계/크레인 인형 뽑기 게임/jaeheon.js, 1단계/키패드 누르기/jaeheon.js, 1단계/햄버거 만들기/jaeheon.js, 2단계/괄호 회전하기/jaeheon.js, 2단계/구명보트/jaeheon.js
레포 만들기전 풀었던 문제들 올림
체육복: 예외처리 잘하기
구명보트: 투 포인터 활용 기억하기
=> 재헌: 레포 만들기전 풀었던 문제들 올림

1단계/직사각형 별 찍기/jaeheon.js, 1단계/행렬의 덧셈/jaeheon.js
=> 재헌: 행렬의 덧셈, 직사각형 별 찍기

1단계/모의고사/soosan.js, 1단계/비밀지도/soosan.js, 1단계/삼총사/soosan.js, 1단계/숫자 짝꿍/soosan.js, 1단계/신고 결과 받기/soosan.js, 1단계/완주하지 못한 선수/soosan.js, 1단계/직사각형 별 찍기/soosan.js, 1단계/행렬의 덧셈/soosan.js
=> 수산: 행렬의 덧셈, 직사각형 별 찍기

1단계/직사각형 별 찍기/hyeonju.js, 1단계/행렬의 덧셈/hyeonju.js, 2단계/주차 요금 계산/hyeonju.js, 2단계/피로도/hyeonju.js
=> 현주: 행렬의 덧셈, 직사각형 별 찍기

1단계/직사각형 별 찍기/hyunsoo.js, 1단계/행렬의 덧셈/hyunsoo.js
=> 현수: 행렬의 덧셈, 직사각형 별 찍기

1단계/같은 숫자는 싫어/minjeong.js, 1단계/최대공약수와 최소공배수/minjeong.js
최대공약수랑 최소공배수 구하는 방식을 외울 것!!
전엔 stack이라는 배열을 만들어서 넣어 주었는데 새로 풀 땐 그냥 다음 인덱스와 같지 않다면 넣어 주니까 간단하게 풀렸다.
=> 민정: 최대공약수와 최소공배수, 같은 숫자는 싫어

1단계/같은 숫자는 싫어/jaeheon.js, 1단계/최대공약수와 최소공배수/jaeheon.js
최대공약수와 최소공배수: gcd와 lcm을 구하는 여러 알고리즘의 존재 확인, 문제 없음
같은 숫자는 싫어: 배열을 스택처럼 사용, 문제 없음
=> 재헌: 최대공약수와 최소공배수, 같은 숫자는 싫어

1단계/3진법 뒤집기/hyeonju.js, 1단계/예산/hyeonju.js, 1단계/이상한 문자 만들기/hyeonju.js
- toString으로 변환할 수 있는지 몰라서 parseInt로 다 하려다 실패하고 힌트 찾아봄
- 문제없음
- 문제없음
=> 현주: 3진법 뒤집기, 이상한 문자 만들기, 예산

1단계/3진법 뒤집기/minjeong.js, 1단계/예산/minjeong.js, 1단계/이상한 문자 만들기/minjeong.js
=> 민정: 3진법 뒤집기, 이상한 문자 만들기, 예산

1단계/3진법 뒤집기/jaeheon.js, 1단계/예산/jaeheon.js, 1단계/이상한 문자 만들기/jaeheon.js
3진법 뒤집기: 문제 없음
이상한 문자 만들기: 문제 없음
예산: 문제 없음
=> 재헌: 3진법 뒤집기, 이상한 문자 만들기, 예산

1단계/시저 암호/jaeheon.js, 1단계/최소 직사각형/jaeheon.js, 1단계/크기가 작은 부분 문자열/jaeheon.js
시저 암호: 아스키 코드 활용
최소 직사각형: "모든 명함을 수납할 수 있는 가장 작은 지갑"의 조건 잘 생각해보기
크기가 작은 부분 문자열: 반복문과 문자열 잘 다루기
=> 재헌: 시저 암호, 최소 직사각형, 크기가 작은 부분 문자열

1단계/시저 암호/minjeong.js, 1단계/최소 직사각형/minjeong.js, 1단계/크기가 작은 부분 문자열/minjeong.js
풀이 방법이 생각나지 않아서 기존에 풀었던 풀이 참고함
=> 민정: 시저 암호, 최소 직사각형, 크기가 작은 부분 문자열

1단계/두 개 뽑아서 더하기/hyunsoo.js, 1단계/문자열 내 마음대로 정렬하기/hyunsoo.js, 1단계/숫자 문자열과 영단어/hyunsoo.js
sort로 numbers를 미리 정렬하고 for문 돌릴 때랑 for문 돌리고 나서 정렬하는게 어떤 차이가 있는지,,
=> 현수: 숫자 문자열과 영단어, 문자열 내 마음대로 정렬하기, 두 개 뽑아서 더하기

1단계/두 개 뽑아서 더하기/hyeonju.js, 1단계/문자열 내 마음대로 정렬하기/hyeonju.js, 1단계/숫자 문자열과 영단어/hyeonju.js
문자열 내 마음대로 정렬하기 : 힌트
나머지 : 문제없음
=> 현주: 숫자 문자열과 영단어, 문자열 내 마음대로 정렬하기, 두 개 뽑아서 더하기

1단계/두 개 뽑아서 더하기/jaeheon.js, 1단계/문자열 내 마음대로 정렬하기/jaeheon.js, 1단계/숫자 문자열과 영단어/jaeheon.js
숫자 문자열과 영단어: 노가다로 해결, 문제 없음
문자열 내 마음대로 정렬하기: localeCompare 사용 가능(난 안씀), 문제 없음
두 개 뽑아서 더하기: Set 사용, 문제 없음
=> 재헌: 숫자 문자열과 영단어, 문자열 내 마음대로 정렬하기, 두 개 뽑아서 더하기

1단계/두 개 뽑아서 더하기/minjeong.js, 1단계/문자열 내 마음대로 정렬하기/minjeong.js, 1단계/숫자 문자열과 영단어/minjeong.js
=> 민정: 숫자 문자열과 영단어, 문자열 내 마음대로 정렬하기, 두 개 뽑아서 더하기

1단계/가장 가까운 같은 글자/jaeheon.js, 1단계/콜라 문제/jaeheon.js, 1단계/푸드 파이트 대회/jaeheon.js
푸드 파이트 대회: 문제 없음
가장 가까운 같은 글자: 문제 없음
콜라 문제: 문제 없음
=> 재헌: 푸드 파이트 대회, 가장 가까운 같은 글자, 콜라 문제

1단계/가장 가까운 같은 글자/minjeong.js, 1단계/콜라 문제/minjeong.js, 1단계/푸드 파이트 대회/minjeong.js
=> 민정 1단계 푸드 파이트 대회, 가장 가까운 같은 글자, 콜라 문제

1단계/가장 가까운 같은 글자/hyeonju.js, 1단계/콜라 문제/hyeonju.js, 1단계/푸드 파이트 대회/hyeonju.js
콜라 문제 : 통과 안 돼서 힌트 봄
나머지 : 문제없음
=> 현주: 푸드 파이트 대회, 가장 가까운 같은 글자, 콜라 문제

1단계/2016년/minjeong.js, 1단계/추억 점수/minjeong.js
=> 민정 1단계 추억 점수, 2016년

.gitignore, 1단계/2016년/hyunsoo.js, 1단계/추억 점수/hyunsoo.js
추억에 점수가 어딨어
비슷한 답 외에 다르게 풀어보고 싶어서 지랄해봤지만 지랄만 하다 끝남
=> 현수: 추억 점수, 2016년

1단계/과일 장수/minjeong.js, 1단계/명예의 전당 (1)/minjeong.js, 1단계/폰켓몬/minjeong.js
**폰켓몬**
독해력 이슈
**명예의 전당(1)**
score의 길이가 k보다 적을 때의 경우도 생각해야 함
**과일 장수**
굳이 새로운 배열을 만들 필요 없었다
=> 민정: 1단계 폰켓몬, 명예의 전당(1), 과일 장수

1단계/과일 장수/jaeheon.js, 1단계/명예의 전당 (1)/jaeheon.js, 1단계/폰켓몬/jaeheon.js
폰켓몬: 문제 없음
명예의 전당(1): 문제 없음
과일 장수: 문제 없음
=> 재헌: 폰켓몬, 명예의 전당(1), 과일 장수

1단계/명예의 전당 (1)/hyeonju.js, 1단계/폰켓몬/hyeonjus.js
=> 현주: 폰켓몬, 명예의 전당(1)

1단계/소수 만들기/minjeong.js, 1단계/소수 찾기/minjeong.js, 1단계/카드 뭉치/minjeong.js
**카드 뭉치**
주어진 배열을 전부 사용하지 않는 경우도 생각했어야 했음.
**소수 만들기, 소수 찾기**
에라토스테네스의 체를 사용하기
이전 풀이들 참고.
=> 민정 1단계 카드 뭉치, 소수 만들기, 소수 찾기

1단계/소수 만들기/jaeheon.js, 1단계/소수 찾기/jaeheon.js, 1단계/카드 뭉치/jaeheon.js
카드 뭉치: 문제 없음
소수 만들기: 문제 없음
소수 찾기: 에라토스테네스의 체를 이용 , 이거 모르면 못푸는 문제
=> 재헌: 카드 뭉치, 소수 만들기, 소수 찾기

1단계/과일 장수/hyeonju.js, 1단계/소수 만들기/hyeonju.js, 1단계/소수 찾기/hyeonju.js, 1단계/카드 뭉치/hyeonju.js
=> 현주: 과일장수, 카드 뭉치, 소수 만들기, 소수 찾기

1단계/다트 게임/minjeong.js, 1단계/덧칠하기/minjeong.js
=> 민정 1단계 덧칠하기, 다트 게임

1단계/다트 게임/jaeheon.js, 1단계/덧칠하기/jaeheon.js
덧칠하기: 문제 없음
다트 게임: 생각보다 좀 복잡하게 느꼈던 문제
=> 재헌: 덧칠하기, 다트 게임 

1단계/과일 장수/hyunsoo.js, 1단계/기사단원의 무기/hyunsoo.js, 1단계/다트 게임/hyunsoo.js, 1단계/덧칠하기/hyunsoo.js, 1단계/소수 만들기/hyunsoo.js, 1단계/소수 찾기/hyunsoo.js, 1단계/카드 뭉치/hyunsoo.js
=> 현수: 덧칠하기, 다트 게임 외

1단계/기사단원의 무기/minjeong.js, 1단계/로또의 최고 순위와 최저 순위/minjeong.js
**기사단원의 무기**
약수 찾는 부분을 다르게 하고 싶었는데 결국 이전 풀이를 보게 됨
**로또의 최고 순위와 최저 순위**
예전 풀이가 너무 노가다였던 것 같아서 최대한 간단하게 하고 싶었음
=> 민정: 기사단원의 무기, 로또의 최고 순위와 최저 순위

1단계/기사단원의 무기/jaeheon.js, 1단계/로또의 최고 순위와 최저 순위/jaeheon.js
기사단원의 무기: 약수의 개수 구하는 효율적인 방법 알아야함, 문제 없음
로또의 최고 순위와 최저 순위: 문제 없음
=> 재헌: 기사단원의 무기, 로또의 최고 순위와 최저 순위

1단계/기사단원의 무기/hyeonju.js
기사단원의 무기 : 시간초과로 Math.sqrt()사용 힌트 참고
로또의 최고 순위와 최저 순위 : 다음 스터디에 다시 올리겠습니다~
=> 현주: 기사단원의 무기

1단계/로또의 최고 순위와 최저 순위/hyunsoo.js
=> 현수: 기사단원의 무기, 로또의 최고 순위와 최저 순위

1단계/문자열 나누기/hyunsoo.js, 1단계/옹알이 (2)/hyunsoo.js
질문하기 등 풀이 참고. 자꾸 생각할 필요 없는 것 까지 고려하지 말자~~
=> 현수: 옹알이(2), 문자열 나누기

1단계/문자열 나누기/minjeong.js, 1단계/옹알이 (2)/minjeong.js
**옹알이 (2)**
다른 방법으로 하려고 노력해 봤는데... 도저히 생각이 안 나서 포기
=> 민정 1단계 옹알이 (2), 문자열 나누기

1단계/문자열 나누기/jaeheon.js, 1단계/옹알이 (2)/jaeheon.js
=> 재헌: 옹알이(2), 문자열 나누기

1단계/로또의 최고 순위와 최저 순위/hyeonju.js, 1단계/문자열 나누기/hyeonju.js, 1단계/옹알이 (2)/hyeonju.js
=> 현주: 로또의 최고 순위와 최저 순위, 옹알이(2), 문자열 나누기

1단계/대충 만든 자판/jaeheon.js, 1단계/둘만의 암호/jaeheon.js
=> 재헌: 대충 만든 자판, 둘만의 암호

1단계/대충 만든 자판/hyeonju.js, 1단계/둘만의 암호/hyeonju.js
=> 현주: 둘만의 암호, 대충 만든 자판

1단계/성격 유형 검사하기/jaeheon.js, 1단계/신규 아이디 추천/jaeheon.js
신규 아이디 추천: 문제 없음
성격 유형 검사하기: 문제 없음
=> 재헌: 신규 아이디 추천, 성격 유형 검사하기

1단계/성격 유형 검사하기/hyeonju.js, 1단계/신규 아이디 추천/hyeonju.js
성격 유형 검사하기 : 푸는중
신규 아이디 추천 : 정규표현식 검색해서 풀었음
=> 현주: 성격 유형 검사하기, 신규 아이디 추천

1단계/개인정보 수집 유효 기간/jaeheon.js, 1단계/바탕화면 정리/jaeheon.js
바탕화면 정리: 문제 없음
개인정보 수집 유효기간: 문제 없음
=> 재헌: 바탕화면 정리 , 개인정보 수집 유효기간

1단계/개인정보 수집 유효 기간/minjeong.js, 1단계/바탕화면 정리/minjeong.js
=> 민정 1단계 바탕화면 정리, 개인정보 수집 유효기간

1단계/바탕화면 정리/hyunsoo.js, 1단계/성격 유형 검사하기/hyunsoo.js, 1단계/신규 아이디 추천/hyunsoo.js
질문하기 풀이 참고함
지난번 못올린 문제 포함
남은 못올린 문제 다음 pr에 올리겠습니다
=> 현수: 신규 아이디 추천, 성격 유형 검사하기, 바탕화면 정리

1단계/개인정보 수집 유효 기간/hyeonju.js, 1단계/바탕화면 정리/hyeonju.js, 1단계/성격 유형 검사하기/hyeonju.js
바탕화면 정리 : 문제없음
개인정보 수집 유효기간 : 못 품, 정답코드 확인
=> 현주: 바탕화면 정리, 개인정보 수집 유효 기간

1단계/공원 산책/jaeheon.js, 1단계/달리기 경주/jaeheon.js
달리기 경주: 해시를 이용해야하는 문제, 일반적인 탐색은 시간초과
공원 산책: 문제 없음
=> 재헌: 달리기 경주, 공원산책

1단계/공원 산책/minjeong.js, 1단계/달리기 경주/minjeong.js
=> 민정 1단계 공원 산책, 달리기 경주

1단계/공원 산책/hyeonju.js, 1단계/달리기 경주/hyeonju.js
달리기 경주 : 시간초과 실패, 정답코드 참고
공원 산책 : 실패, 정답코드 참고
=> 현주: 달리기 경주, 공원산책

0단계/구슬을 나누는 경우의 수/minjeong.js, 0단계/배열 만들기 4/minjeong.js, 2단계/최댓값과 최솟값/minjeong.js
**구슬을 나누는 경우의 수**
DFS 생각이 매번 안 남... 사실 아직도 이해 안 된 듯
=> 민정: 배열 만들기 4, 구슬을 나누는 경우의 수, 최댓값과 최솟값

0단계/구슬을 나누는 경우의 수/jaeheon.js, 0단계/배열 만들기 4/jaeheon.js, 2단계/최댓값과 최솟값/jaeheon.js
배열 만들기 4: 문제 없음
구슬을 나누는 경우의 수: 아마도 부동소수점 문제 때문에 조금 헤맴 
최댓값과 최솟값: 문제 없음
=> 재헌: 배열 만들기 4, 구슬을 나누는 경우의 수, 최댓값과 최솟값

0단계/구슬을 나누는 경우의 수/hyeonju.js, 0단계/배열 만들기 4/hyeonju.js, 2단계/최댓값과 최솟값/hyeonju.js
구슬 : math.round 힌트 참고
나머지 : 문제없음
=> 현주: 최댓값과 최솟값, 배열만들기4, 구슬을 나누는 경우의 수

0단계/두 수의 합/jaeheon.js, 0단계/삼각형의 완성 조건 (2)/jaeheon.js, 2단계/JadenCase 문자열 만들기/jaeheon.js
삼각형의 완성조건 (2): BigInt 사용 안하고 해본 것도 추가, 문제 없음
두 수의 합: 문제 없음
JadenCase 문자열 만들기: 문제 없음
=> 재헌: 삼각형의 완성조건 (2), 두 수의 합, JadenCase 문자열 만들기

0단계/두 수의 합/hyeonju.js, 0단계/삼각형의 완성 조건 (2)/hyeonju.js, 2단계/JadenCase 문자열 만들기/hyeonju.js
두 수의 합 : BigInt 메서드 검색
JadenCase : 런타임에러로 공백 문자열 힌트 참고
삼각형의 완성 조건 : 문제 없음
=> 현주: 두 수의 합, 삼각형의 완성 조건, JadenCase문자열 만들기

0단계/구슬을 나누는 경우의 수/hyunsoo.js, 0단계/두 수의 합/hyunsoo.js, 0단계/삼각형의 완성 조건 (2)/hyunsoo.js, 2단계/JadenCase 문자열 만들기/hyunsoo.js
=> 현수: 두 수의 합, 삼각형의 완성 조건, JadenCase문자열 만들기

0단계/왼쪽 오른쪽/jaeheon.js, 0단계/조건 문자열/jaeheon.js, 2단계/최솟값 만들기/jaeheon.js
왼쪽 오른쪽: 문제 없음 
조건 문자열: 문제 없음
최솟값 만들기: 그냥 이렇게 해봤는데 되네??
=> 재헌: 왼쪽 오른쪽, 조건 문자열, 최솟값 만들기

0단계/문자열 여러 번 뒤집기/jaeheon.js, 0단계/배열 만들기 6/jaeheon.js, 2단계/올바른 괄호/jaeheon.js
배열 만들기 6: 문제 없음
문자열 여러 번 뒤집기: 문제 없음 
올바른 괄호: 문제 없음
=> 재헌: 배열 만들기 6, 문자열 여러 번 뒤집기, 올바른 괄호

0단계/문자열 여러 번 뒤집기/minjeong.js, 0단계/배열 만들기 6/minjeong.js, 0단계/수열과 구간 쿼리 2/minjeong.js, 2단계/올바른 괄호/minjeong.js
수열과 구간 쿼리 이번에 푸는 건 줄 알고 더 풀었어요..........................
=> 민정: 배열 만들기 6, 수열과 구간 쿼리 2, 올바른 괄호, 문자열 여러 번 뒤집기

0단계/문자열 여러 번 뒤집기/hyeonju.js, 0단계/배열 만들기 6/hyeonju.js, 2단계/올바른 괄호/hyeonju.js
=> 현주: 배열만들기 6, 문자열 여러 번 뒤집기, 올바른 괄호

0단계/a와 b 출력하기/minjeong.js, 0단계/외계어 사전/minjeong.js, 0단계/정사각형으로 만들기/minjeong.js, 2단계/숫자의 표현/minjeong.js, 2단계/이진 변환 반복하기/minjeong.js
수열 어쩌구는 지난 번에 올렸음.
**이진 변환 반복하기**: 지난 풀이 참고
=> 민정: 정사각형으로 만들기, 이진 변환 반복하기

0단계/수열과 구간 쿼리 2/jaeheon.js, 0단계/정사각형으로 만들기/jaeheon.js, 2단계/이진 변환 반복하기/jaeheon.js
정사각형으로 만들기: 문제 없음
수열과 구간 쿼리(2): 문제 없음
이진 변환 반복하기: 문제 없음
=> 재헌: 정사각형으로 만들기, 수열과 구간 쿼리(2), 이진 변환 반복하기

0단계/수열과 구간 쿼리 2/hyunsoo.js, 0단계/정사각형으로 만들기/hyunsoo.js
이진 변환 반복하기는 풀던 중이라 다음 pr에 같이 올릴게요! 나머지 문제 없음
=> 현수: 정사각형으로 만들기, 수열과 구간 쿼리(2)

0단계/a와 b 출력하기/hyunsoo.js, 0단계/외계어 사전/hyunsoo.js, 2단계/숫자의 표현/hyunsoo.js, 2단계/이진 변환 반복하기/hyunsoo.js
=> 현수: 이진 변환 반복하기, a와 b 출력하기, 외계어 사전, 숫자의 표현

0단계/a와 b 출력하기/jaeheon.js, 0단계/외계어 사전/jaeheon.js, 2단계/숫자의 표현/jaeheon.js
a와 b 출력하기: 문제 없음
외계어 사전: 문제 없음
숫자의 표현: 그냥 풀면 시간초과, 투 포인터 인가 슬라이딩 윈도우인가 기법 사용
=> 재헌: a와 b 출력하기, 외계어 사전, 숫자의 표현

0단계/무작위로 K개의 수 뽑기/jaeheon.js, 0단계/문자열 겹쳐 쓰기/jaeheon.js, 2단계/다음 큰 숫자/jaeheon.js
작위로 K개의 수 뽑기: 문제 없음
문자열 겹쳐 쓰기: 문제 없음
다음 큰 숫자: 문제 없음
=> 재헌: 무작위로 K개의 수 뽑기, 문자열 겹쳐 쓰기, 다음 큰 숫자

0단계/그림 확대/hyunsoo.js, 0단계/종이 자르기/hyunsoo.js, 0단계/직사각형 넓이 구하기/hyunsoo.js, 0단계/캐릭터의 좌표/hyunsoo.js, 2단계/짝지어 제거하기/hyunsoo.js, 2단계/피보나치 수/hyunsoo.js
=> 현수: 캐릭터의 좌표, 종이 자르기, 피보나치 수

0단계/종이 자르기/jaeheon.js, 0단계/캐릭터의 좌표/jaeheon.js, 2단계/피보나치 수/jaeheon.js
캐릭터의 좌표: 문제 없음
종이 자르기: 문제 없음
피보나치 수: 재귀 X, dp 문제, 1234567 어이 없음
=>  재헌: 캐릭터의 좌표, 종이 자르기, 피보나치 수

0단계/그림 확대/hyunsoo.js, 0단계/직사각형 넓이 구하기/hyunsoo.js, 2단계/짝지어 제거하기/hyunsoo.js
짝지어 제거하기 시간 초과 풀이참고
이전 pr들 머지하기 전에 푸시 해버려서 파일 내용이 온전히 안보일 수 있음,,ㅜ
=> 현수: 직사각형 넓이 구하기, 그림 확대, 짝지어 제거하기

0단계/그림 확대/jaeheon.js, 0단계/직사각형 넓이 구하기/jaeheon.js, 2단계/짝지어 제거하기/jaeheon.js
그림 확대: 문제 없음
직사각형 넓이 구하기: 문제 없음
짝지어 제거하기: 스택 사용, 문제 없음
=> 재헌: 그림 확대, 직사각형 넓이 구하기, 짝지어 제거하기

0단계/로그인 성공/jaeheon.js, 0단계/치킨 쿠폰/jaeheon.js, 2단계/카펫/jaeheon.js
로그인 성공: 문제 없음
치킨 쿠폰: 문제 없음
카펫: 문제 없음
=> 재헌: 로그인 성공, 치킨 쿠폰, 카펫

0단계/로그인 성공/hyunsoo.js, 0단계/치킨 쿠폰/hyunsoo.js, 2단계/카펫/hyunsoo.js
=> 현수: 로그인 성공, 치킨 쿠폰, 카펫

0단계/로그인 성공/minjeong.js, 0단계/치킨 쿠폰/minjeong.js, 2단계/카펫/minjeong.js
=> 민정: 로그인 성공, 치킨 쿠폰, 카펫

0단계/대소문자 바꿔서 출력하기/jaeheon.js, 0단계/등수 매기기/jaeheon.js, 2단계/영어 끝말잇기/jaeheon.js
등수 메기기: 문제 없음
대소문자 바꿔서 출력하기: 문제 없음
영어 끝말잇기: 문제 없음
=> 재헌: 등수 메기기, 대소문자 바꿔서 출력하기, 영어 끝말잇기

0단계/대소문자 바꿔서 출력하기/hyunsoo.js, 0단계/등수 매기기/hyunsoo.js, 2단계/영어 끝말잇기/hyunsoo.js
=> 현수: 등수 매기기, 영어 끝말잇기, 대소문자 바꿔서 출력하기

0단계/유한소수 판별하기/jaeheon.js, 0단계/저주의 숫자 3/jaeheon.js, 2단계/구명보트/jaeheon.js
유한소수 판별하기: 문제 없음
저주의 숫자 3: 문제 없음
구명보트: 다시 푼 문제,  문제 없음
=>  재헌: 유한소수 판별하기, 저주의 숫자 3, 구명보트

0단계/유한소수 판별하기/hyunsoo.js, 0단계/저주의 숫자 3/hyunsoo.js, 2단계/구명보트/hyunsoo.js
=> 현수: 유한소수 판별하기, 저주의 숫자 3, 구명보트

0단계/전국 대회 선발 고사/jaeheon.js, 0단계/특이한 정렬/jaeheon.js, 2단계/예상 대진표/jaeheon.js
전국 대회 선발 고사: 문제 없음
특이한 정렬: 문제 없음
예상 대진표: 문제 없음
=> 재헌: 전국 대회 선발 고사, 특이한 정렬, 예상 대진표

0단계/문자열 밀기/jaeheon.js, 0단계/배열 만들기 2/jaeheon.js, 2단계/점프와 순간 이동/jaeheon.js
문자열 밀기: 문제 없음
배열 만들기2: 문제 없음
점프와 순간이동: 문제 없음
=> 재헌: 문자열 밀기, 배열 만들기2, 점프와 순간이동

0단계/문자열 밀기/minjeong.js, 0단계/배열 만들기 2/minjeong.js, 2단계/점프와 순간 이동/minjeong.js
=> 민정: 배열 만들기2, 문자열 밀기, 점프와 순간 이동

0단계/다항식 더하기/hyunsoo.js, 0단계/최빈값 구하기/hyunsoo.js, 2단계/N개의 최소공배수/hyunsoo.js
=> 현수: 다항식 더하기, 최빈값 구하기, N개의 최소공배수

0단계/다항식 더하기/hyeonju.js, 0단계/문자열 밀기/hyeonju.js, 0단계/배열 만들기 2/hyeonju.js, 0단계/최빈값 구하기/hyeonju.js, 2단계/N개의 최소공배수/hyeonju.js, 2단계/점프와 순간 이동/hyeonju.js
=> 현주: 배열 만들기2, 문자열 밀기, 점프와 순간 이동, 다항식 더하기, 최빈값 구하기, N개의 최소공배수

0단계/문자열 출력하기/jaeheon.js, 0단계/코드 처리하기/jaeheon.js, 2단계/멀리 뛰기/jaeheon.js
코드 처리하기: 문제 없음
문자열 출력하기: 문제 없음
멀리 뛰기: 몇개 노가다로 해보니까 규칙을 발견해서 적용
=> 재헌: 코드 처리하기, 문자열 출력하기, 멀리 뛰기

0단계/문자열 출력하기/minjeong.js, 0단계/코드 처리하기/minjeong.js, 2단계/멀리 뛰기/minjeong.js
**멀리 뛰기**
피보나치인 건 알겠어... 알겠기만 하겠어...
=> 민정: 코드 처리하기, 문자열 출력하기, 멀리 뛰기

0단계/문자열 출력하기/hyeonju.js, 0단계/코드 처리하기/hyeonju.js, 2단계/멀리 뛰기/hyeonju.js, 2단계/이진 변환 반복하기/hyeonju.js
=> 현주: 코드 처리하기, 문자열 출력하기, 멀리 뛰기

0단계/OX 퀴즈/jaeheon.js, 0단계/다음에 올 숫자/jaeheon.js, 0단계/배열 조각하기/jaeheon.js, 2단계/괄호 회전하기/jaeheon.js, 2단계/귤 고르기/jaeheon.js
OX 퀴즈: 문제 없음
귤 고르기: 문제 없음
다음에 올 숫자: 문제 없음
배열 조각하기: 문제 없음
괄호 회전하기: 코드 조금 바꿔봄, 문제 없음
=> 재헌: OX 퀴즈, 귤 고르기, 다음에 올 숫자, 배열 조각하기, 괄호 회전하기

0단계/OX 퀴즈/minjeong.js, 0단계/다음에 올 숫자/minjeong.js, 0단계/배열 조각하기/minjeong.js, 2단계/귤 고르기/minjeong.js
=> 민정: OX 퀴즈, 배열 조각하기, 다음에 올 숫자, 귤 고르기

0단계/다음에 올 숫자/hyeonju.js, 0단계/배열 조각하기/hyeonju.js, 2단계/괄호 회전하기/hyeonju.js
=> 현주: 배열 조각하기, 다음에 올 숫자, 괄호 회전하기

0단계/분수의 덧셈/minjeong.js, 0단계/연속된 수의 합/minjeong.js, 2단계/연속 부분 수열 합의 개수/minjeong.js
=> 민정: 분수의 덧셈, 연속된 수의 합, 연속 부분 수열 합의 개수
